spring:
  redis:
    host: localhost
#    database: ${REDIS_DB:0}
#    host: ${REDIS_HOST:127.0.0.1}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PWD:}
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10s
#    cluster:
#      nodes: 123
#      max-redirects: 5
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 5m
      key-prefix: 'boot:data.redisson:'
