spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#
#    publisher-returns: true
#    publisher-confirm-type: correlated
#    virtual-host: /
#    listener:
#      type: simple
#      simple:
#        acknowledge-mode: auto #确认模式
#        prefetch: 1 #限制每次发送一条数据。
#        concurrency: 3 #同一个队列启动几个消费者
#        max-concurrency: 3 #启动消费者最大数量
#        #重试策略相关配置
#        retry:
#          # 开启消费者(程序出现异常)重试机制，默认开启并一直重试
#          enabled: true
#          # 最大重试次数
#          max-attempts: 5
#          # 重试间隔时间(毫秒)
#          initial-interval: 3000
#          # 重试最大间隔时间(毫秒)
#          max-interval: 30000