https:
  connectionTimeout: 50
  keepAliveTimeout: 10
  readTimeout: 10000
  writeTimeout: 10000
  callTimeout: 10000

feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true

  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
        defaultQueryParameters: { foo: bar }
        defaultRequestHeaders: { adc: test, mate: de }
        requestInterceptors:
          - me.boot.httputil.interceptor.TraceInterceptor
#        decode404: false
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract


logging:
  level:
    me.boot: debug

boot:
  name: httpBin