server:
  servlet:
    context-path: /${spring.application.name}
  shutdown: graceful
  http2:
    enabled: true
  compression:
    enabled: true

  undertow:
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
      # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
      worker: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true

  tomcat:
    accept-count: 100
    threads:
      # 1核2g内存为200,4核8g内存为800
      max: 800
      # 最小空闲线程数量
      min-spare: 100

    basedir: /log
    access-log:
      directory: tomcat
      file-date-format: .yyyy-MM-dd
#      enabled: true



spring:
  config:
    import:
#      - classpath:application.yml
      - optional:D:\Code\Mine\boot-demo\http-util\src\main\resources\application.yml

  application:
    name: web


  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**


  mvc:
    async:
      request-timeout: 30000
    format:
      date: iso
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss


  web:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    #    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: NON_NULL #不为空的属性才会序列化
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    deserialization:
      #      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: true


  jpa:
    hibernate:
      # 自动创建、更新、验证数据库表结构
      ddl-auto: update
    open-in-view: true
    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        new_generator_mappings: false
#        format_sql: true
      show-sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            store_data_at_delete: true


#  datasource:
#    url: jdbc:h2:./web/src/main/resources/data;NON_KEYWORDS=USER
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2



springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false
  writer-with-order-by-keys: true
  default-support-form-data: true

  swagger-ui:
    enabled: true
    filter: true
#    operationsSorter: method
    tagsSorter: alpha
    displayOperationId: true
    displayRequestDuration: true
    docExpansion: none
    showExtensions: true
    showCommonExtensions: true
    persistAuthorization: true



