spring:
  application:
    name: demo-config

  config:
    import:
      - optional:nacos:demo-config

  cloud:
    nacos:
      # Nacos Config 配置项，对应 NacosConfigProperties 配置属性类
      config:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
#        namespace: # 使用的 Nacos 的命名空间，默认为 null
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
#        name: # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
        file-extension: yaml # 使用的 Nacos 配置

        # 拓展配置集数组，对应 Config 数组
        extension-configs:
          - data-id: extension-dataId.yaml
            group: DEFAULT_GROUP
            refresh: true # 是否自动刷新配置，默认为 false

        # 共享配置集数组，对应 Config 数组
        shared-configs:
          - data-id: shared-dataId.yaml
            group: DEFAULT_GROUP
            refresh: true # 是否自动刷新配置，默认为 false
